name: Format

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  format:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Run dotnet format
        run: dotnet format whitespace --exclude 'Maple2.Server.World/Migrations/*.cs'

      - name: Commit changes
        if: github.event_name != 'pull_request' || github.repository == github.event.pull_request.head.repo.full_name
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format whitespace"
